more progress

diff --git a/om-install.d/0000_check_preqs.in b/om-install.d/0000_check_preqs.in
--- a/om-install.d/0000_check_preqs.in
+++ b/om-install.d/0000_check_preqs.in
@@ -1,24 +1,26 @@
+#!/bin/bash
 function checkPreqs {
-    required_tools=( ruby git ssh ssh-keygen rrdtool nmap collectd graphviz redis-server )
+    required_tools=( ruby git ssh ssh-keygen rrdtool nmap collectd graphviz redis-server iftop pidgin mtr )
     log "Checking system for required tools & libraries...\n"
-    debug "\$PATH is set to: $PATH\n"
+    debug "PATH is set to: $PATH\n"
 
-    # check tools, special threatment for ruby
+    # check tools, special treatment for ruby
     missing_tools=()
+    local tool
 	for tool in "${required_tools[@]}"
 	do
 	    if [ "$tool" = "ruby" ]; then continue; fi
  		if ! which $tool > /dev/null 2>&1
  		then
-    			log-red "Couldn't find '$tool' in $PATH\n" >&2
+    			debug "Couldn't find '$tool' in $PATH\n" >&2
     			missing_tools=("${missing_tools[@]} $tool")
     			ret=1
  		fi
 	done
 
 	# TODO ruby command may be provided by PATH or .rvm
-    if ! which ruby > /dev/null 2>&1 ;
-        then debug "Couldn't find 'ruby' in $PATH\n" >&2 ;
+    if ! which ruby > /dev/null 2>&1 ; then
+        debug "Couldn't find 'ruby' in $PATH\n" >&2 ;
         missing_tools=("${missing_tools[@]} ruby")
         ret=1;
     fi
@@ -29,14 +31,14 @@ function checkPreqs {
 
 	# some tools are missing
 	if [ $ret = 1 ] ; then
-	    debug "Missing tools:${missing_tools[@]}\n"
-		log-red "Whoops! This system lacks software needed to run Openmetrics: \n"
+	    #echo "Missing tools: ${missing_tools[@]}"
+		log-red "Whoops! This system lacks software needed to run Openmetrics.\n"
 		while true; do
 		    read -p "I'll try to fix this for you. Ok? [$dialogInstallPreqs]: "; evalYesNo dialogInstallPreqs
         done
         return 1
 	fi
 
-	# prerequisits check succeeded
+	# prerequisites check succeeded
 	return 0
 }
